# Simple workflow for building and deploying markdown files using staticgen
name: "staticgen build"
description: Builds markdown files to html static site
author: Jashon Osala
inputs:
  url:
    description: "Base url for the repos github-pages"
    required: true
    default: ""
  build:
    description: "Path of directory to output build"
    required: false
    default: "build"
  md:
    description: "Path of directory containing markdown files"
    required: true
    default: "markdown"
  artifact_name:
    description: "Artifact name"
    required: false
    default: "staticgen"
  
  # Generate build files 
runs:
    using: composite
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install staticgen
        shell: bash
        run: |
          git clone -n https://github.com/osala-eng/developer-challange.git /tmp/staticgen --depth 1
          export POS=$(PWD)
          cd /tmp/staticgen
          git checkout HEAD static-site-generator
          cd static-site-generator
          sudo ./install
          cd $POS
          rm -rf /tmp/staticgen
      - name: Generate build
        shell: bash
        run: sudo staticgen --deploy-to-github "${MD_PATH}" "$BUILD_PATH" "${INPUT_URL}"
        env:
          INPUT_URL: ${{ inputs.url }}
          MD_PATH: ${{ inputs.md }}
          BUILD_PATH: ${{ inputs.build }}
      
      # Upload build artifacs
      - name: Upload build using upload page artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ inputs.build }}
          name: ${{ inputs.artifact_name }}
branding:
  icon: activity
  color: red
